### ISSUE TITLE
PDS3 filesystem issues w/ furia

### ISSUE THREAD

**Issue by emuchicken** [henrikstengaard/hstwb-installer#30]
I installed betterwb, runs fine in WinUAE- but when in an A600 and using the Furia card, it crashes upon boot.  My other card (with classicwb / SFS) runs fine.  Is it possible to convert to SFS/PFS3 without loss of data?  - Is there a PFS3 install hdf?

**Comment by henrikstengaard** [comment]
Unfortunately there is no easy way of converting from one filesystem to another on an Amiga.

In your case, it sounds more like an issue with your hdd or scsi.device used together with your Furia card. I have a Furia card myself in my A600 and it's very picky about CF cards and brands. Instead of CF cards I use SD card using an IDE to SD adapter bought on ebay. This solution works fine.

Then if your image if larger 4GB, then a patched scsi.device is required for your A600 to access more than 4GB. Such patched scsi.device is included in some of the packages like ClassicWB and HstWB. Otherwise you could use a Kickstart 3.1.4 rom which comes with updated support for large harddisks. But this does also require Amiga OS 3.1.4 to run properly.

Whats the size of your image?
What Kickstart rom do you have in yourA600?
What type of harddisk and brand are you using in your A600?

**Comment by emuchicken** [comment]
3.1 kickroms, ... BTW: Found the issue wasn't the PFS, it seems to be the mini loader that crashes (which 
 before starting workbench).  I need to experiment a bit more tbh
